In [1]:
import faiss
import numpy as np

In [43]:
# Generate random data
data = np.random.rand(1000, 128).astype('float32')
print(data.shape, '\n\n', data)

(1000, 128) 

 [[0.68231803 0.672493   0.03956196 ... 0.2579528  0.4973178  0.12742965]
 [0.9183969  0.45814905 0.5569934  ... 0.4695651  0.7910698  0.5670189 ]
 [0.82816917 0.0675278  0.9924135  ... 0.280343   0.09878639 0.26395375]
 ...
 [0.8385078  0.6971204  0.05211771 ... 0.3526199  0.04197034 0.45220876]
 [0.41486168 0.84772927 0.712509   ... 0.68154246 0.624566   0.69358087]
 [0.33777028 0.44267955 0.4348719  ... 0.52701426 0.27906212 0.45661286]]


In [44]:
# Create an index
index = faiss.IndexFlatL2(128)

index

<faiss.swigfaiss.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x000001BCFC636610> >

In [45]:
# Add data to the index
index.add(data)

In [46]:
index.ntotal

1000

In [47]:
# Perform a similarity search
query_vector = np.random.rand(1, 128).astype('float32')
query_vector

array([[0.7883648 , 0.41136336, 0.9411829 , 0.4793632 , 0.47632456,
        0.28983968, 0.04203349, 0.289745  , 0.732191  , 0.5562675 ,
        0.75870293, 0.3889537 , 0.4016068 , 0.7716787 , 0.25878546,
        0.04279917, 0.56189305, 0.13955125, 0.9904803 , 0.8158495 ,
        0.2786525 , 0.57010424, 0.6887196 , 0.31815043, 0.32157892,
        0.88693696, 0.87979895, 0.5991045 , 0.580945  , 0.644616  ,
        0.56092095, 0.50649965, 0.9495719 , 0.9772402 , 0.23074982,
        0.5430632 , 0.27663183, 0.23790276, 0.11169199, 0.05266745,
        0.45226702, 0.8725337 , 0.45916864, 0.09133863, 0.42283416,
        0.47331154, 0.50781566, 0.05439515, 0.93841547, 0.66182554,
        0.9071043 , 0.7235043 , 0.22964306, 0.94322455, 0.66576266,
        0.35312515, 0.12344145, 0.19621372, 0.22748429, 0.08112133,
        0.63714504, 0.20912836, 0.659002  , 0.4967138 , 0.5027035 ,
        0.8627106 , 0.81616676, 0.07222863, 0.9442593 , 0.1850456 ,
        0.03661183, 0.37136742, 0.38819668, 0.96

In [48]:
k = 5  # Number of nearest neighbors to retrieve
distances, indices = index.search(query_vector, k)

print(distances, '\n\n', indices)

[[15.230064 15.299754 15.325577 15.770106 15.788852]] 

 [[548 141 881 945 559]]


In [30]:
# Print the results
print("Nearest neighbors:")
for i in range(k):
    print(f"Neighbor {i+1}: Index {indices[0][i]}, Distance {distances[0][i]}")

Nearest neighbors:
Neighbor 1: Index 154, Distance 13.626096725463867
Neighbor 2: Index 987, Distance 14.77947998046875
Neighbor 3: Index 326, Distance 14.900426864624023
Neighbor 4: Index 448, Distance 15.060054779052734
Neighbor 5: Index 956, Distance 15.383966445922852


Using wrapper class IndexIDMap()

In [2]:
import uuid
import random
import numpy as np

In [ ]:
with open("../data/")
index_to_uuid = 
len(index_to_uuid)

In [3]:
def uuid_to_integer(uuid_str):
    uuid_obj = uuid.UUID(uuid_str)
    return int(uuid_obj)

In [6]:
uuid.uuid4().int

152995461970103006715204532270574363546

In [31]:
uuid_str = uuid.uuid4().hex
uuid_str
uuid_int = int(uuid_str, 16)
uuid_int

180936446031768742176339095938439056364

In [8]:
# Assuming you have data with ids, pdf_names, content, and content_vectors
# Replace ta
# hese with your actual data
ids = np.array([])
# [random.randint(1000000000000000000, 9999999999999999999) for _ in range(4)]
pdf_names = np.array(["document1.pdf", "document2.pdf", "document3.pdf", "document4.pdf"])
contents = np.array(["Lorem ipsum...", "Some content...", "More text...", "Another document..."])
content_vectors = np.random.rand(4, 128).astype('float32')

print(ids)
print(9999999999999999999-1000000000000000000)

['31901521815047459272' '48129387037837680675' '83629329901949053646'
 '69650343604485036160']
8999999999999999999


In [9]:
len("31901521815047459272")

20

In [5]:
content_vectors.shape

(4, 128)

In [6]:
print(ids, type(ids))

['31901521815047459272' '48129387037837680675' '83629329901949053646'
 '69650343604485036160'] <class 'numpy.ndarray'>


In [7]:
# Create an index with an ID map
index = faiss.IndexIDMap(faiss.IndexFlatL2(128))

# Add data to the index
index.add_with_ids(content_vectors, ids)

OverflowError: int too big to convert

In [76]:
index.ntotal

4

In [64]:
# Now you can perform similarity search based on vectors
query_vector = np.random.rand(128).astype('float32')

query_vector.reshape(1, -1)

array([[0.6366048 , 0.93784165, 0.9124456 , 0.97283703, 0.68820465,
        0.02372937, 0.7721488 , 0.58758307, 0.5522444 , 0.75899285,
        0.01946464, 0.28351074, 0.68345416, 0.883433  , 0.46650502,
        0.7660906 , 0.5268666 , 0.561976  , 0.12070926, 0.60223705,
        0.38173473, 0.0785682 , 0.22157276, 0.10268464, 0.80028266,
        0.747212  , 0.46652105, 0.3438265 , 0.03773617, 0.32861012,
        0.47929502, 0.45830628, 0.6758675 , 0.52527815, 0.05083382,
        0.10023683, 0.60241264, 0.50144666, 0.77939206, 0.8419433 ,
        0.5986357 , 0.9484357 , 0.70691556, 0.5732267 , 0.849358  ,
        0.71512735, 0.66208935, 0.75337553, 0.4227825 , 0.4569677 ,
        0.85512555, 0.90606177, 0.24346267, 0.55773   , 0.01029735,
        0.32267365, 0.32378623, 0.7280866 , 0.14991273, 0.0113767 ,
        0.6550192 , 0.9749685 , 0.5131942 , 0.20251061, 0.9371011 ,
        0.90294397, 0.08195505, 0.300796  , 0.47309244, 0.4844724 ,
        0.76858646, 0.86672425, 0.8846436 , 0.74

In [65]:
k = 2  # Number of nearest neighbors
distances, neighbors = index.search(query_vector.reshape(1, -1), k)

In [66]:
print(distances, '\n\n', neighbors)

[[19.132317 20.620216]] 

 [[50362476835 58841892270]]


In [101]:
neighbors[0]

array([2, 3], dtype=int64)

In [102]:
# Access metadata for the top neighbors
top_ids = neighbors[0]
top_pdf_names = pdf_names[top_ids]
top_contents = contents[top_ids]

print("Top IDs:", top_ids)
print("Top PDF Names:", top_pdf_names)
print("Top Contents:", top_contents)

Top IDs: [2 3]
Top PDF Names: ['document3.pdf' 'document4.pdf']
Top Contents: ['More text...' 'Another document...']


In [90]:
# just for illustration purpose
pdf_names = np.array(["document1.pdf", "document2.pdf", "document3.pdf", "document4.pdf"])
selected_pdf_names = pdf_names[[2, 1, 3, 0]]

print(selected_pdf_names)

['document3.pdf' 'document2.pdf' 'document4.pdf' 'document1.pdf']


utilizing metadata

In [35]:
# Assuming you have data with ids, pdf_names, content, and content_vectors
# Replace these with your actual data
ids = np.array(["0", "1", "2", "3"])
pdf_names = np.array(["document1.pdf", "document2.pdf", "document3.pdf", "document4.pdf"])
contents = np.array(["Lorem ipsum...", "Some content...", "More text...", "Another document..."])
content_vectors = np.random.rand(4, 128).astype('float32')

# Create an index with an ID map
index = faiss.IndexIDMap(faiss.IndexFlatL2(128))

# Add data to the index
index.add_with_ids(content_vectors, ids)


In [36]:
index.ntotal

0

In [5]:
# Create a metadata dictionary to store content and pdf_names
metadata = {id: {'pdf_name': pdf_name, 'content': content} for id, pdf_name, content in zip(ids, pdf_names, contents)}

metadata

{'0': {'pdf_name': 'document1.pdf', 'content': 'Lorem ipsum...'},
 '1': {'pdf_name': 'document2.pdf', 'content': 'Some content...'},
 '2': {'pdf_name': 'document3.pdf', 'content': 'More text...'},
 '3': {'pdf_name': 'document4.pdf', 'content': 'Another document...'}}

In [6]:
# Perform similarity search
query_vector = np.random.rand(128).astype('float32')
k = 3  # Number of nearest neighbors
distances, neighbors = index.search(query_vector.reshape(1, -1), k)

In [7]:
query_vector

array([0.05836474, 0.21127205, 0.49519885, 0.28718567, 0.9235771 ,
       0.16406272, 0.33702028, 0.13646674, 0.9895277 , 0.46299663,
       0.27912527, 0.0666471 , 0.28890687, 0.01501042, 0.6818322 ,
       0.8926095 , 0.12463351, 0.84303   , 0.7116783 , 0.33055183,
       0.41794163, 0.11810032, 0.09094615, 0.20593594, 0.57114595,
       0.82305217, 0.7836236 , 0.03082706, 0.6476728 , 0.29392973,
       0.394905  , 0.7680704 , 0.6378382 , 0.0501974 , 0.5268558 ,
       0.96009505, 0.85917515, 0.4694897 , 0.20646133, 0.34803727,
       0.45567253, 0.79031056, 0.03574383, 0.4732567 , 0.845975  ,
       0.37967634, 0.3652112 , 0.73336965, 0.25416017, 0.46735397,
       0.9836752 , 0.41234314, 0.43725112, 0.37731108, 0.55959815,
       0.73756266, 0.3734922 , 0.5932459 , 0.40928006, 0.7762083 ,
       0.14701259, 0.60498774, 0.90800667, 0.11148183, 0.25173268,
       0.08770949, 0.5693294 , 0.77718776, 0.7062066 , 0.04542087,
       0.46582213, 0.10674249, 0.9423862 , 0.47272992, 0.88635

In [24]:
# Retrieve and print metadata for the top neighbors
top_ids = neighbors[0]
for id in top_ids:
    metadata_entry = metadata[f"{id}"]
    print(f"ID: {id}, PDF Name: {metadata_entry['pdf_name']}, Content: {metadata_entry['content']}")

ID: 2, PDF Name: document3.pdf, Content: More text...
ID: 3, PDF Name: document4.pdf, Content: Another document...
ID: 1, PDF Name: document2.pdf, Content: Some content...


trying to save and load index

In [7]:
import faiss
import json

In [18]:
def create_index(vector_size):
    id_map_index = faiss.IndexIDMap(faiss.IndexFlatL2(vector_size))
    return id_map_index
    
def save_index(index, index_path):
    try:
        faiss.write_index(index, index_path)
        return True
    except:
        return False
    
def load_index(index_path):
    id_map_index = faiss.read_index(index_path)
    return id_map_index

In [19]:
id_map_index_c500 = create_index(768)

In [20]:
save_index(id_map_index_c500, "../faiss_index/id_map_index_c500.faiss")

True

In [5]:
id_map_index_c500 = load_index("../faiss_index/id_map_index_c500.faiss")

id_map_index_c500

<faiss.swigfaiss.IndexIDMap; proxy of <Swig Object of type 'faiss::IndexIDMapTemplate< faiss::Index > *' at 0x000002398771CE40> >

In [6]:
id_map_index_c500.ntotal

0

In [25]:
import faiss
import numpy as np
import json

class Faiss:
    def __init__(self):
        self.index_path = "../faiss_index/id_map_index_c500.faiss"

    def create_index(self, vector_size):
        index = faiss.IndexIDMap(faiss.IndexFlatL2(vector_size))

        return index
    
    def save_index(self, index):
        try:
            faiss.write_index(index, self.index_path)
            return True
        except:
            return False
        
    def load_index(self):
        index = faiss.read_index(self.index_path)

        return index
    
    def append_index(self, id, pdf_name):
        print(f"id {id} loading index") # print

        index = self.load_index()

        print(f"id {id} index loaded") # print

        with open(f"../data/chunked_embedded_pdfs/{id}.json", "r") as file:
            chunked_embedded_pdf = json.load(file)

        print(f"id {id} chunked_embedded_pdf read!") # print

        pdf_content_vector = chunked_embedded_pdf["pdf_content_vector"]

        ids = []

        for count in range(len(pdf_content_vector)):
            ids.append(f"{id}_{count}")  

        print("checking if len(ids) != len(pdf_content_vector)") # print

        if len(ids) != len(pdf_content_vector):
            return False

        print("converting ids and pdf_content_vector to np.array!") # print

        ids = np.array(ids)
        pdf_content_vector = np.array(pdf_content_vector)

        print("ids", ids, type(ids))
        # print("pdf_content_vector", pdf_content_vector)

        try:
            print("populating index with chunks") # print

            index.add_with_ids(pdf_content_vector, ids)

            print("populating index SUCCESSFUL, now saving index!!") # print

            result = self.save_index(index)

            if result:
                print("saving index successful") # print
                return pdf_name
            else:
                return False
        except Exception as e:
            print(e)
            return False
        
    def search_index(self, conversation_id, embedded_query, k):
        index = self.load_index(self, self.index_path)

        distances, neighbors = index.search(embedded_query.reshape(1, -1), k)

        top_ids = neighbors[0]

        return top_ids
    
    def get_context(self, conversation_id, top_ids):
        context = []

        for top_id in top_ids:
            id = top_id.split("_")[0]
            chunk_id = top_id.split("_")[1]

            with open(f"../data/chunked_embedded_pdfs/{id}.json", "r") as file:
                chunked_embedded_pdf = json.load(file)

            context.append(chunked_embedded_pdf["pdf_content"][chunk_id])

        return context


In [26]:
fiass = Faiss()

In [27]:
result = fiass.append_index("75d494fbc3534eea837af24dd6d9f8b9", "ABSLI-Assured-Savings-Plan-Brochure-Web-Version-V07")

id 75d494fbc3534eea837af24dd6d9f8b9 loading index
id 75d494fbc3534eea837af24dd6d9f8b9 index loaded
id 75d494fbc3534eea837af24dd6d9f8b9 chunked_embedded_pdf read!
checking if len(ids) != len(pdf_content_vector)
converting ids and pdf_content_vector to np.array!
ids ['75d494fbc3534eea837af24dd6d9f8b9_0' '75d494fbc3534eea837af24dd6d9f8b9_1'
 '75d494fbc3534eea837af24dd6d9f8b9_2' '75d494fbc3534eea837af24dd6d9f8b9_3'
 '75d494fbc3534eea837af24dd6d9f8b9_4' '75d494fbc3534eea837af24dd6d9f8b9_5'
 '75d494fbc3534eea837af24dd6d9f8b9_6' '75d494fbc3534eea837af24dd6d9f8b9_7'
 '75d494fbc3534eea837af24dd6d9f8b9_8' '75d494fbc3534eea837af24dd6d9f8b9_9'
 '75d494fbc3534eea837af24dd6d9f8b9_10'
 '75d494fbc3534eea837af24dd6d9f8b9_11'
 '75d494fbc3534eea837af24dd6d9f8b9_12'
 '75d494fbc3534eea837af24dd6d9f8b9_13'
 '75d494fbc3534eea837af24dd6d9f8b9_14'
 '75d494fbc3534eea837af24dd6d9f8b9_15'
 '75d494fbc3534eea837af24dd6d9f8b9_16'
 '75d494fbc3534eea837af24dd6d9f8b9_17'
 '75d494fbc3534eea837af24dd6d9f8b9_18'
 '75d494f

In [21]:
result

False

In [42]:
import uuid

def uuid_to_integer(uuid_str):
    uuid_obj = uuid.UUID(uuid_str)
    return int(uuid_obj)

# Example usage
uuid_str = '550e8400-e29b-41d4-a716-446655440000'
integer_value = uuid_to_integer(uuid_str)
print(integer_value)
print("113059749145936325402354257176981405696")

113059749145936325402354257176981405696
113059749145936325402354257176981405696


In [43]:
uuid_to_integer('550e8400-e29b-41d4-a716-446655440001')

113059749145936325402354257176981405697

In [44]:
uuid_to_integer('550e8400-e29b-41d4-a716-446655440001')

113059749145936325402354257176981405697

In [45]:
uuid_str1 = '550e8400-e29b-41d4-a716-446655440000'
uuid_str2 = '550e8400-e29b-41d4-a716-446655440001'

# Convert UUIDs to integers
integer_value1 = uuid_to_integer(uuid_str1)
integer_value2 = uuid_to_integer(uuid_str2)

print(f"UUID: {uuid_str1}, Integer: {integer_value1}")
print(f"UUID: {uuid_str2}, Integer: {integer_value2}")

UUID: 550e8400-e29b-41d4-a716-446655440000, Integer: 113059749145936325402354257176981405696
UUID: 550e8400-e29b-41d4-a716-446655440001, Integer: 113059749145936325402354257176981405697


In [44]:
import json

In [32]:
index = faiss.read_index("../faiss_index/id_map_index_c500.faiss")
index.ntotal

0

In [1]:
import faiss
import numpy as np
import json

class Faiss:
    def __init__(self):
        self.index_path = "../faiss_index/id_map_index_c500.faiss"

    def create_index(self, vector_size):
        index = faiss.IndexIDMap(faiss.IndexFlatL2(vector_size))

        return index
    
    def save_index(self, index):
        try:
            faiss.write_index(index, self.index_path)
            return True
        except:
            return False
        
    def load_index(self):
        index = faiss.read_index(self.index_path)

        return index
    
    def append_index(self, id, pdf_name):
        print(f"id {id} loading index") # print

        index = self.load_index()

        print(f"id {id} index loaded") # print

        with open(f"../data/chunked_embedded_pdfs/{id}.json", "r") as file:
            chunked_embedded_pdf = json.load(file)

        print(f"id {id} chunked_embedded_pdf read!") # print

        pdf_content_vector = chunked_embedded_pdf["pdf_content_vector"]

        start_id = index.ntotal

        ids = [start_id + count + 1 for count in range(len(pdf_content_vector))]

        chunk_ids = [f"{id}_{count}" for count in range(len(pdf_content_vector))]

        print("ids", ids, "\n")
        print("chunk_ids", chunk_ids)

        # for count in range(len(pdf_content_vector)):
        #     ids.append(f"{id}_{count}")  

        print("checking if len(ids) != len(pdf_content_vector)") # print

        if len(ids) != len(pdf_content_vector):
            return False
        
        print("checking if len(ids) != len(chunk_ids)") # print

        if len(ids) != len(chunk_ids):
            return False

        print("converting ids and pdf_content_vector to np.array!") # print

        # ids = np.array(ids)
        # pdf_content_vector = np.array(pdf_content_vector)

        try:
            print("populating index with chunks") # print

            index.add_with_ids(np.array(pdf_content_vector), np.array(ids))

            print("populating index SUCCESSFUL, now saving index!!") # print

            result = self.save_index(index)

            if result:
                print("saving index successful") # print
                
                print("updating id_uuid_chunk_mapping.json") # print
                try:
                    with open("../data/id_uuid_chunk_mapping.json", 'r') as file:
                        id_uuid_chunk_mapping = json.load(file)
                except:
                    id_uuid_chunk_mapping = {}

                print("update loop running................")
                for id, chunk_id in zip(ids, chunk_ids):
                    id_uuid_chunk_mapping[str(id)] = chunk_id

                print("loop done")
                with open("../data/id_uuid_chunk_mapping.json", 'w') as file:
                    json.dump(id_uuid_chunk_mapping, file)

                return pdf_name
            else:
                return False
        except:
            return False
        
    def search_index(self, conversation_id, embedded_query, k):
        index = self.load_index(self, self.index_path)

        distances, neighbors = index.search(embedded_query.reshape(1, -1), k)

        top_ids = neighbors[0]

        return top_ids
    
    def get_context(self, conversation_id, top_ids):
        context = []
        context_chunk_ids = []

        with open("../data/id_uuid_chunk_mapping.json", "r") as file:
            id_uuid_chunk_mapping = json.load(file)

        for top_id in top_ids:
            if str(top_id) in id_uuid_chunk_mapping:
                context_chunk_ids.append(id_uuid_chunk_mapping[str(top_id)])
        
        for top_chunk_id in context_chunk_ids:
            id = top_chunk_id.split("_")[0]
            chunk_id = top_chunk_id.split("_")[1]

            with open(f"../data/chunked_embedded_pdfs/{id}.json", "r") as file:
                chunked_embedded_pdf = json.load(file)

            context.append(chunked_embedded_pdf["pdf_content"][chunk_id])

        return context


In [7]:
f = Faiss()
test = f.append_index("a1cd1af4667148a1be086f8c77126beb", "test")
test

id a1cd1af4667148a1be086f8c77126beb loading index
id a1cd1af4667148a1be086f8c77126beb index loaded
id a1cd1af4667148a1be086f8c77126beb chunked_embedded_pdf read!
ids [165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205] 

chunk_ids ['a1cd1af4667148a1be086f8c77126beb_0', 'a1cd1af4667148a1be086f8c77126beb_1', 'a1cd1af4667148a1be086f8c77126beb_2', 'a1cd1af4667148a1be086f8c77126beb_3', 'a1cd1af4667148a1be086f8c77126beb_4', 'a1cd1af4667148a1be086f8c77126beb_5', 'a1cd1af4667148a1be086f8c77126beb_6', 'a1cd1af4667148a1be086f8c77126beb_7', 'a1cd1af4667148a1be086f8c77126beb_8', 'a1cd1af4667148a1be086f8c77126beb_9', 'a1cd1af4667148a1be086f8c77126beb_10', 'a1cd1af4667148a1be086f8c77126beb_11', 'a1cd1af4667148a1be086f8c77126beb_12', 'a1cd1af4667148a1be086f8c77126beb_13', 'a1cd1af4667148a1be086f8c77126beb_14', 'a1cd1af4667148a1be086f8c77126beb_15', '

'test'

In [8]:
index = f.load_index()
index.ntotal

205

In [5]:
# index.reset()

In [9]:
index.ntotal

205

In [10]:
import faiss
import numpy as np

# Create a Faiss index
dimension = 128
index = faiss.IndexFlatL2(dimension)

# Add vectors to the index (example)
vectors = np.random.random((100, dimension)).astype('float32')  # Example vectors
index.add(vectors)

# Check the value of ntotal before resetting the index
print("Before reset, ntotal:", index.ntotal)

# Reset the index
index.reset()

# Check the value of ntotal after resetting the index
print("After reset, ntotal:", index.ntotal)

# Repopulate the index with the same documents
index.add(vectors)

# Check the value of ntotal after repopulating the index
print("After repopulating, ntotal:", index.ntotal)




Before reset, ntotal: 100
After reset, ntotal: 0
After repopulating, ntotal: 100


In [13]:
index.reset()
start_id = index.ntotal
print(start_id)
ids = [start_id + count + 1 for count in range(0, 100)]
print(ids)
index.reset()
print("index reset")
vectors = np.random.random((100, dimension)).astype('float32')  # Example vectors
index.add(vectors)
ids = [start_id + count + 1 for count in range(0, 100)]
print(ids)

0
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
index reset
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


In [17]:
index.

AttributeError: 'IndexFlatL2' object has no attribute 'pdf_name'